# Generated by Django 4.0.5 on 2022-09-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balfordisp',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='proid',
        ),
    ]
